version: '3.8'

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: .docker/api/Dockerfile
    restart: always
    network_mode: host
    environment:
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - TARGET_EMAIL=${TARGET_EMAIL}
  
  front:
    container_name: front
    build:
      context: .
      dockerfile: .docker/front/Dockerfile
    restart: always
    network_mode: host