name: CI/CD sp-1

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build API image
        run: |
          docker build \
            -f .docker/api/Dockerfile \
            --build-arg SMTP_USER=${{ secrets.SMTP_USER }} \
            --build-arg SMTP_PASSWORD=${{ secrets.SMTP_PASSWORD }} \
            --build-arg TARGET_EMAIL=${{ secrets.TARGET_EMAIL }} \
            -t api .

      - name: Build Front image
        run: |
          docker build \
            -f .docker/front/Dockerfile \
            -t front .

      - name: Deploy
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd /root/Security_page_1
            git pull origin main
            docker-compose down
            docker-compose up -d --build
